### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by mmilardic** [RimacTechnology/style-guide#23]
### Issues

- [X] I have checked [existing issues](https://github.com/RimacTechnology/style-guide/issues) and there are no issues with the same problem.

### `@RimacTechnology/style-guide` Version You Are Using

8.0.1

### Your Config

/** @type { import('@types/eslint').ESLint.ConfigData } */
module.exports = {
    extends: [require.resolve('@rimac-technology/style-guide/eslint/core')],
    ignorePatterns: [
        '*generated*',
        'coverage',
        '**/kafka/**/contract/*.ts',
        'dist',
    ],
    overrides: [
        {
            extends: [require.resolve('@rimac-technology/style-guide/eslint/jest')],
            files: ['**/*.test.ts'],
        },
    ],
    parser: '@typescript-eslint/parser',
    parserOptions: {
        project: './tsconfig.lint.json',
    },
}

### Steps to reproduce

In oem-dashboard-core-api run: yarn lint

### Expected behavior

Warning should not appear. Some eslint dependencies in this package seem not to be matching the typescript-estree (es2022) version in the oem-dashboard-core-repo.
Similar issue described here:
https://stackoverflow.com/questions/72789233/warning-you-are-currently-running-a-version-of-typescript-which-is-not-official

### Actual behavior

We get the following warning:
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.1.0

YOUR TYPESCRIPT VERSION: 5.1.3

Please only submit bug reports when using the officially supported version

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by vuki656** [comment]
We are 3 patch versions in front of the supported version. Shouldn't be a problem.
